
<template>
  <div>
    <div class="flex flex-wrap justify justify-center">
      <div class="w-full text-center">
        <h1 class="mt-10">{{$t('TermsAndCond')}}</h1>

        <p class="p-10 md:p-20 desc text-left"v-if="$i18n.locale == 'en'">
          The use of the website services is available only to persons who are able to legally represent themselves. People who are unable to legally represent themselves according to the local contract system cannot use the website services. If you are a minor (for example, if you are less than 18 years old), you can use the services of the website under the supervision of a parent or legal guardian, provided that he agrees to abide by the terms of use. The user will be responsible for his use of the website services, in full compliance with the local laws in that region. These terms and conditions are considered valid and null for the previous forms of commercial representation, verbal agreements, or other understandings, unless additional conditions are specified in this regard for a specific product or service. <br><br>
          By using the website services, you will be obligated to follow the terms and conditions. <br>
           The registration process includes the information (your personal information) that you provide to us to complete your transactions and also to contact you. You must accept the principle of using and updating your personal information in order to deal with the registration process and to control the confidentiality of your identity during the follow-up process to deliver the purchase order and pay electronically. The information that you provide during the registration process is protected data in accordance with the terms of the privacy protection described previously. Your personal information forms part of your record of your dealings with our services. If you use our website, you will be responsible for maintaining the confidentiality of your personal account and password, in addition to preventing access to your personal device / computer, and you thus bear responsibility for all operations that are performed through your personal account using the password. <br>
          The website does not bear any liability to anyone for any loss or damage that may arise due to your failure to protect your password or any other information related to your personal account. <br>
          In our constant and relentless endeavor to provide accurate and comprehensive information about our products (such as product availability, prices, product specifications, pictograms, technical characteristics) and to provide comprehensive information about services, we may encounter some typographical errors. <br>
          The maximum accuracy limits are taken into account in displaying the colors of the products on the website, but what you see of the colors visible on the site depends mainly on the settings of your screen and this falls outside the scope of our competence as we cannot be sure of the approved color settings on your screen. <br>
          Publication of details related to products or services (including but not limited to: marketing brochures, advertisements, commercial offers, magazine offers and small publications) on the website is not considered a guarantee of the availability of products, offers or prices, whether through online shopping or in the exhibition directly. Some errors may occur during the process of providing the product or service and providing detailed information about prices on the website. The website cannot provide you with individual product prices or know the total cost of the product or service until you complete your online order. In the event that the invoice was requested and issued for a product or service and the price was incorrect or the information was incorrect due to an error in recording the correct price or product or service information, then the website has the right in this case to either contact you to clarify this error and how to deal with it or cancel your order and Notice of this cancellation
          <br><br>
          Delivery within 48 working hours except Friday (not a working day) as well as official holidays such as Eid and National Day. <br><br>
          . Delivery also depends on customer acceptance and scheduling the delivery date with the shipping team. In the event that the customer cannot be contacted at the specified time, then there will be a delay in the delivery of the shipment without any liability on the company. <br>
          Our payment system includes several methods / forms of payment methods: <br>
          • For online payments (online): we accept payments via SADAD payment system, credit cards (Visa or MasterCard only) /. In the case of online payment, the customer will receive a notification on the screen as soon as the payment is accepted. We are not responsible if the payment process is rejected or canceled by the credit card service provider for any reason. You must check with the bank providing the credit card service about the reason for the rejection. We do not store your credit card information on the website. All information and details that you enter through the electronic payment gateway are encrypted for the purpose of security protection, and the correspondence from and to the service provider’s website is also encrypted. We do not provide any of the payment information made through the site to other companies or individual entities unless it is requested by an official legal authority. This information is processed by our payment officer. <br>
          You must ensure that the information related to your credit card that you use to pay for electronic services is correct, valid and accurate, and you must use the credit card legally affiliated with you. Your personal information will not be used or shared by electronic services with any third party, with the exception of verifying the legitimacy of the information and not falsifying it or when requested by the law or legal systems or at the request of the court. The website service (online) will not be responsible in any way for credit card fraud. <br>
          You will be held responsible for the use of fraudulent credit cards and you will be entirely responsible for proving otherwise. In the event that we are not able to provide the request or part of it, we will inform you directly in this regard. All or part of the amount paid by the credit card you used to pay the order amount will be refunded, partial payments are not refundable. Your use of the online payment service for our website constitutes an implicit consent to your commitment to these terms. If you do not agree to any clause of these terms, please do not use this service
         </p>
        <p class="p-10 md:p-20 desc text-left" v-else>


          إن استخدام خدمات الموقع الإلكتروني متاحة فقط للأشخاص القادرين على تمثيل أنفسهم قانونياً . لايمكن للأشخاص غير القادرين على تمثيل أنفسهم قانونيا وفق نظام العقود المحلي استخدام خدمات الموقع الإلكتروني. إن كنت قاصرا ( كأن يكون عمرك أقل من 18 سنة) فبإمكانك استخدام خدمات الموقع الإلكتروني تحت إشراف أحد الوالدين أو الوصي القانوني شريطة موافقته الالتزام ببنود شروط الاستخدام. سيكون المستخدم مسؤولاً عن استخدامه خدمات الموقع وذلك بالتزامه التام بالقوانين المحلية المتبعة في تلك المنطقة. هذه الشروط والأحكام تعتبر سارية المفعول ولاغية لما قبلها من أشكال التمثيل التجاري أو الاتفاقيات الشفهية أو غيرها من المفاهمات مالم يخصص بهذا الشأن شروط اضافية خاصة بمنتج معين أو خدمة محددة.
          <br><br>

          باستخدامك لخدمات الموقع الإلكتروني ستكون ملزماً باتباع بنود الشروط والأحكام.
           <br><br>
          تتضمن عملية التسجيل المعلومات (معلوماتك الشخصية) التي تزودنا بها لإتمام معاملاتك و أيضاً للإتصال بك. يجب عليك القبول بمبدأ استخدامنا لمعلوماتك الشخصية وتحديثها وذلك للتعامل مع عملية التسجيل وللتحكم بسرية هويتك خلال عملية المتابعة لتسليم طلب الشراء والدفع الكترونياً. إن المعلومات الي تقدمها خلال عملية التسجيل هي بيانات محمية وفقاً لبنود حماية الخصوصية الموضحة سابقاً. تشكل معلوماتك الشخصية جزءا من سجلك الخاص لتعاملاتك مع خدماتنا. في حالة استخدامك لموقعنا الإلكتروني ستكون مسؤولاً عن المحافظة على سرية حسابك الشخصي و كلمة المرور بالإضافة إلى منع الوصول الى جهازك الشخصي/ جهاز الكمبيوتر وأنت بذلك تتحمل المسؤولية عن جميع العمليات التي يتم تنفيذها من خلال حسابك الشخصي باستخدام كلمة المرور<br>.
          لايتحمل الموقع الإلكتروني أي مسؤولية تجاه أي شخص عن أي خسارة أو أضرار قد تنشأ بسبب فشلك في حماية كلمة المرور الخاصة بك أو أي معلومات أخرى متعلقة بحسابك الشخصي<br>
          في سعينا الدائم والحثيث لتقديم معلومات دقيقة وشاملة عن منتجاتنا ( مثل توفر المنتج و الأسعار و مواصفات المنتجات و الصور التوضيحية والخصائص الفنية) و تقديم معلومات شاملة عن الخدمات، قد تصادفنا بعض الأخطاء المطبعية.
          يتم مراعاة أقصى حدود الدقة في عرض ألوان المنتجات في الموقع الإلكتروني ، ولكن ما تراه من ألوان ظاهرة في الموقع يعتمد بشكل أساسي على إعدادات شاشتك وهذا يقع خارج نطاق صلاحيتنا حيث لا يمكننا التاكد بشكل جازم من إعدادات الألوان المعتمدة في شاشتك.
          إن نشرالتفاصيل المتعلقة بالمنتجات أو الخدمات ( يتضمن ولكن لا يقتصر على: نشرات التسويق و الإعلانات والعروض التجارية وعروض المجلات والمنشورات الصغيرة) على الموقع الإلكتروني لا يعتبر ضماناً على توفر المنتجات أو العروض أو الأسعار سواء من خلال التسوق الإلكتروني أو في المعرض بطريق مباشر. قد تحدث بعض الأخطاء خلال عملية توفير المنتج أو الخدمة وتوفير المعلومات التفصيلية عن الأسعار على الموقع الإلكتروني. لايمكن للموقع الإلكتروني تزويدك بأسعار المنتجات بشكل منفرد أو معرفة التكلفة الإجمالية للمنتج أو الخدمة حتى تقوم بتسليم طلبك الإلكتروني كاملاً. في حال تم طلب وإصدار الفاتورة لمنتج أو خدمة و كان السعر غير صحيح أو كانت المعلومات غير صحيحة لورود خطأ في تسجيل السعر الصحيح أو معلومات المنتجات أو الخدمات فيحق للموقع الإلكتروني في هذه الحالة إما أن يتواصل معك لتوضيح هذا الخطأ وكيفية التعامل معه أو إلغاء طلبك و إشعارك بهذا الإلغاء.
          <br><br>
          التوصيل خلال 48 ساعة عمل ما عدا يوم الجمعة (ليس يوم عمل) كذلك أيام العطل الرسمية مثل أيام العيد واليوم الوطني.
          <br><br>
          . التوصيل كذلك يعتمد على قبول العميل وتحديد موعد التوصيل مع فريق الشحن. في حال أن العميل لا يمكن الاتصال به في الموعد المحدد عندها سيحصل تأخير بتوصيل الشحنة دون أدنى مسؤولية على شركة أوتانتك.
          <br><br>
          ان نظام الدفع لدينا يتضمن عدة طرق/ أشكال من أساليب الدفع:
          <br>
          • لعمليات الدفع من خلال الانترنت (أونلاين)  : نقبل الدفع عن طريق نظام سداد للمدفوعات ,البطاقات الإئتمانية ( فيزا أو ماستر كارد فقط) /. في حالة الدفع عن طريق الانترنت ( أونلاين) سيستلم العميل إشعارا على الشاشة فور قبول عملية الدفع. لانتحمل أي مسؤولية لو تم رفض عملية الدفع أو إلغائها من قبل مزود خدمة البطاقة الإئتمانية لأي سبب من الأسباب. يجب عليك التأكد من البنك المزود لخدمة البطاقة الإئتمانية عن سبب الرفض. نحن لانقوم بتخزين معلومات بطاقتك الإئتمانية على الموقع الإلكتروني.إن جميع المعلومات والتفاصيل التي تقوم بإدخالها من خلال بوابة الدفع الإلكترونية يتم تشفيرها بغرض الحماية الأمنية، ويتم أيضا تشفير المراسلات المتداولة من و إلى موقع مقدم الخدمة. لانقوم بتقديم أي من معلومات الدفع التي تمت عن طريق الموقع إلى شركات أخرى أو جهات فردية إلا إذا تم طلبها من قبل جهة رسمية قانونية. تتم معالجة هذه المعلومات من قبل مأمور الدفع لدينا.
          <br><br>
          يجب عليك التأكد من المعلومات المتعلقة ببطاقتك الإئتمانية التي تستخدمها في الدفع للخدمات الإلكترونية بأن تكون صحيحة و سارية المفعول والتزام الدقة ، ويجب عليك استخدام البطاقة الإئتمانية التابعة قانونيا لك. لن يتم استخدام أو مشاركة معلوماتك الشخصية من قبل الخدمات الإلكترونية مع أي طرف ثالث ويستثنى من ذلك التحقق من شرعية المعلومات وعدم تزويرها أو عند طلبها من القانون أو الأنظمة الشرعية أو بطلب من المحكمة. لن تكون خدمة الموقع الإلكتروني (أونلاين) مسؤولة بأي شكل من الأشكال عن تزوير البطاقات الإئتمانية.
          سيتم تحميلك كافة المسؤوليات عن استخدام البطاقات الإئتمانية المزورة وستكون مسؤولا بشكل كامل عن اثبات خلاف ذلك. في حال عدم تمكننا من توفير الطلب أو جزء منه فسنبلغك مباشرة بهذا الخصوص . سيتم إرجاع كامل أو جزء من المبلغ المدفوع بواسطة البطاقة الإئتمانية التي استخدمتها لدفع مبلغ الطلب، لايمكن رد المدفوعات الجزئي. إن استخدامك لخدمة الدفع الإلكتروني (أونلاين) لموقعنا الإلكتروني هو بمثابة موافقة ضمنية لالتزامك بهذه الشروط .في حال عدم موافقتك لأي بند من بنود هذه الشروط فنرجوا منك عدم استخدام هذه الخدمة

         </p>

      </div>
    </div>
  </div>
</template>

<style lang="scss">
  .desc {
    line-height: 2;
  }
</style>
